Batch http headers
simple-odata-client/Simple.OData.Client pull request #788
Opened 2021-02-05 18:48 UTC by nsarris

@watfordgnf I found a way to test the batch headers by intercepting the http request through settings. This is a version without any functional changes. Some whitespace changes here are there are from VS auto formatting. Otherwise its pretty lean and straight forward.

2021-02-06 13:40 UTC, object requested changes
I have just a code styling comment. The class BatchWriteBase has several member variables (_session, _ entryMap etc.) and all of them are currently using underscode prefix convention. If you extend the class with a new member variable, it's better to keep consistent naming convention rather than using a new one. So I recommend changing the name to _headers to keep it consistent with the rest of the member variables in this class.

2021-02-06 22:43 UTC, nsarris commented
@object I think you meant the ODataBatch class, that's the only one I added a headers field to. Renamed to match convention.

2021-03-05 14:19 UTC, watfordgnf commented on src/Simple.OData.Client.Core/ODataBatch.cs
>          /// <summary>
```suggestion
        private readonly Dictionary<string, string> _headers = new Dictionary<string, string>();
        
        /// <summary>
```

2021-03-05 14:19 UTC, watfordgnf commented on src/Simple.OData.Client.Core/Adapter/BatchWriterBase.cs
> +                    requestMessage.Headers.Add(header.Key, header.Value);
```suggestion
                foreach (var header in headers)
                {
                    requestMessage.Headers.Add(header.Key, header.Value);
                }
```

2021-03-05 14:19 UTC, watfordgnf commented on src/Simple.OData.Client.Core/ODataBatch.cs
> +                WithHeader(header.Key, header.Value);
```suggestion
            foreach (var header in headers)
            {
                WithHeader(header.Key, header.Value);
            }
```

2021-03-05 16:27 UTC, nsarris commented
@watfordgnf all changes commited.

2021-03-06 16:20 UTC, merged